reader: "filesystem"
writer: "filesystem"
plugins: ["markdown", "blank", "tags"]
url_scheme:
    index: ""
    archive: "/archive/"
    tag: "/tag/%slug/"
    post: "/%year/%month/%slug/"
    page: "/%slug/"
    feed: "/feed/"
    error: "/error/"
options:
    reader:
        content: "content"
        extension: "md"
        template: "template"
    writer:
        directory: "site"
    markdown:
        extras: ["tables", "code-highlight"]
    blank:
        generate:
            index: "index"
            archive: "archive"
            feed: "feed"
            error: "error"
